/* eslint-disable */

/**
 * This file was automatically generated by bson-schema-to-typescript.
 * https://www.npmjs.com/package/bson-schema-to-typescript
 *
 * Do not modify it by hand. Instead, modify the MongoDB $jsonSchema validator,
 * and run bson2ts to regenerate this file.
 */

/**
 * User object
 */
export interface UserDoc {
  location?: {
    type: "Point";
    coordinates: [number, number];
    [k: string]: unknown;
  };
}
