/* eslint-disable */

/**
 * This file was automatically generated by bson-schema-to-typescript.
 * https://www.npmjs.com/package/bson-schema-to-typescript
 *
 * Do not modify it by hand. Instead, modify the MongoDB $jsonSchema validator,
 * and run bson2ts to regenerate this file.
 */

/**
 * User object
 */
export interface UserDoc {
  /**
   * String (min 8, max 8, alphanumeric pattern)
   */
  _id: string;
  /**
   * String
   */
  string?: string;
  /**
   * Number
   */
  number?: number;
  /**
   * Integer
   */
  int?: number;
  /**
   * Boolean
   */
  boolean?: boolean;
  /**
   * Null
   */
  null?: null;
  /**
   * Date
   */
  date?: Date;
  /**
   * Multiple types: string
   */
  multipleTypes1?: string;
  /**
   * Multiple types: string, number
   */
  multipleTypes2?: string | number;
  /**
   * Multiple types: string, number, boolean
   */
  multipleTypes3?: string | number | boolean;
  /**
   * Multiple types: string, number, boolean, null
   */
  multipleTypes4?: string | number | boolean | null;
  /**
   * Multiple types: string, number, boolean, null, date
   */
  multipleTypes5?: string | number | boolean | null | Date;
}
