/* eslint-disable */

/**
 * This file was automatically generated by bson-schema-to-typescript.
 * https://www.npmjs.com/package/bson-schema-to-typescript
 *
 * Do not modify it by hand. Instead, modify the MongoDB $jsonSchema validator,
 * and run bson2ts to regenerate this file.
 */
import { Decimal128 } from "mongodb";

/**
 * User object
 */
export interface UserDoc {
  /**
   * String
   */
  string?: string;
  /**
   * Number
   */
  number?: number;
  /**
   * Boolean
   */
  boolean?: boolean;
  /**
   * Null
   */
  null?: null;
  /**
   * Date
   */
  date?: Date;
  /**
   * Decimal
   */
  decimal?: Decimal128;
}
