/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by bson-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run bson-schema-to-typescript to regenerate this file.
 */
import { Decimal128 } from "bson";

/**
 * User object
 */
export interface UserDoc {
  /**
   * String
   */
  string?: string;
  /**
   * Number
   */
  number?: number;
  /**
   * Boolean
   */
  boolean?: boolean;
  /**
   * Null
   */
  null?: null;
  /**
   * Date
   */
  date?: Date;
  /**
   * Decimal
   */
  decimal?: Decimal128;
}
