/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by bson-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run bson-schema-to-typescript to regenerate this file.
 */
import { Decimal128 } from "bson";

/**
 * User object
 */
export interface UserDoc {
  /**
   * Multiple types: string
   */
  multipleTypes1?: string;
  /**
   * Multiple types: string, number
   */
  multipleTypes2?: string | number;
  /**
   * Multiple types: string, number, boolean
   */
  multipleTypes3?: string | number | boolean;
  /**
   * Multiple types: string, number, boolean, null
   */
  multipleTypes4?: string | number | boolean | null;
  /**
   * Multiple types: string, number, boolean, null, date
   */
  multipleTypes5?: string | number | boolean | null | Date;
  /**
   * Multiple types: string, number, boolean, null, date, decimal
   */
  multipleTypes6?: string | number | boolean | null | Date | Decimal128;
}
