/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by bson-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run bson-schema-to-typescript to regenerate this file.
 */

/**
 * User object
 */
export interface UserDoc {
  /**
   * String (min 8, max 8, alphanumeric pattern)
   */
  _id: string;
  /**
   * Date
   */
  createdAt: Date;
  /**
   * Date
   */
  modifiedAt: Date;
}
