import { parseConfig } from "./options";

const defaultOptions = {
  bannerComment: [
    "/* eslint-disable */",
    "/* tslint:disable */",
    "/**",
    "* This file was automatically generated by bson-schema-to-typescript.",
    "* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,",
    "* and run bson-schema-to-typescript to regenerate this file.",
    "*/",
  ],
  enableConstEnums: true,
  ignoreMinAndMaxItems: false,
  strictIndexSignatures: false,
  unknownAny: true,
  path: "src/__generated__",
};

describe("Default options", () => {
  /**
   * JSON.stringify generated inputs
   */

  // Null
  test("null returns default options", () => {
    const config = JSON.stringify(null);
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  // Undefined
  test("undefined returns default options", () => {
    const config = JSON.stringify(undefined);
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  // Boolean
  test("boolean returns default options", () => {
    const config = JSON.stringify(false);
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("boolean returns default options", () => {
    const config = JSON.stringify(true);
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  // Number
  test("number returns default options (JSON)", () => {
    const config = JSON.stringify(1);
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("number returns default options (JSON)", () => {
    const config = JSON.stringify(0);
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("number returns default options (JSON)", () => {
    const config = JSON.stringify(1.1);
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  // Object
  test("empty object returns default options", () => {
    const config = JSON.stringify({});
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  // Array
  test("empty array returns default options", () => {
    const config = JSON.stringify([]);
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("array returns default options", () => {
    const config = JSON.stringify(["1"]);
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  // String
  test("empty string returns default options", () => {
    const config = JSON.stringify("");
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("some string returns default options", () => {
    const config = JSON.stringify("x");
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  /**
   * Plain string inputs
   */
  test("empty string returns default options", () => {
    const config = "";
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("some string returns default options", () => {
    const config = "x";
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("some string returns default options", () => {
    const config = "undefined";
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });
});

describe("Customized options with wrong type", () => {
  test("bannerComment as boolean returns default options", () => {
    const config = JSON.stringify({ bannerComment: true });
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("bannerComment as array of non-strings returns default options", () => {
    const config = JSON.stringify({ bannerComment: [false] });
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("enableConstEnums as string returns default options", () => {
    const config = JSON.stringify({ enableConstEnums: "some string" });
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("ignoreMinAndMaxItems as object returns default options", () => {
    const config = JSON.stringify({ ignoreMinAndMaxItems: { x: 1 } });
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("strictIndexSignatures as null returns default options", () => {
    const config = JSON.stringify({ strictIndexSignatures: null });
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("unknownAny as array returns default options", () => {
    const config = JSON.stringify({ unknownAny: ["1"] });
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });

  test("path as number returns default options", () => {
    const config = JSON.stringify({ path: 1 });
    expect(parseConfig(config)).toStrictEqual(defaultOptions);
  });
});

describe("Customized options", () => {
  test("bannerComment", () => {
    const config = JSON.stringify({ bannerComment: ["some banner"] });
    expect(parseConfig(config)).toStrictEqual({
      ...defaultOptions,
      bannerComment: ["some banner"],
    });
  });

  test("enableConstEnums", () => {
    const config = JSON.stringify({ enableConstEnums: false });
    expect(parseConfig(config)).toStrictEqual({
      ...defaultOptions,
      enableConstEnums: false,
    });
  });

  test("ignoreMinAndMaxItems", () => {
    const config = JSON.stringify({ ignoreMinAndMaxItems: true });
    expect(parseConfig(config)).toStrictEqual({
      ...defaultOptions,
      ignoreMinAndMaxItems: true,
    });
  });

  test("strictIndexSignatures", () => {
    const config = JSON.stringify({ strictIndexSignatures: true });
    expect(parseConfig(config)).toStrictEqual({
      ...defaultOptions,
      strictIndexSignatures: true,
    });
  });

  test("unknownAny", () => {
    const config = JSON.stringify({ unknownAny: false });
    expect(parseConfig(config)).toStrictEqual({
      ...defaultOptions,
      unknownAny: false,
    });
  });

  test("path", () => {
    const config = JSON.stringify({ path: "newPath/" });
    expect(parseConfig(config)).toStrictEqual({
      ...defaultOptions,
      path: "newPath/",
    });
  });
});
